name: docker

on:
    push:
        branches:
            - master
        tags:
            - v*

jobs:
    push:
        runs-on: [ self-hosted ]
        permissions:
            packages: write
            contents: read

        steps:
            - uses: actions/checkout@v3

            - uses: tada5hi/action-docker-image-publish@master
              if: github.ref_type == 'tag'
              with:
                  registryRepository: central
                  registryTag: latest

            - uses: tada5hi/action-docker-image-publish@master
              if: github.ref_type == 'branch'
              with:
                  registryRepository: central
                  registryTag: next
